language: python

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

# The apt packages below are needed for sphinx builds, which can no longer
# be installed with sudo apt-get.
addons:
    apt:
        packages:
            - graphviz
            - texlive-latex-extra
            - dvipng

python:
    - 2.7
    - 3.5
    - 3.6

env:
    global:
        # The following versions are the 'default' for tests, unless
        # overidden underneath. They are defined here in order to save having
        # to repeat them for all configurations.
        - NUMPY_VERSION=1.11 # numpy > 1.11 is not compatible with mpl 1
        - ASTROPY_VERSION=stable
        - CONDA_DEPENDENCIES='matplotlib=1.5 scipy'
        - SPHINX_VERSION=1.5.6 # spectral-cube 0.4.0 won't install with newer versions
        - PIP_DEPENDENCIES='spectral-cube lmfit lineid-plot specutils'

    matrix:
        # Make sure that egg_info works without dependencies
        - SETUP_CMD='egg_info'
        # Try all python versions with the latest numpy
        - SETUP_CMD='test'

matrix:
    include:

        # Check for sphinx doc build warnings - we do this first because it
        # may run for a long time
        - python: 3.6
          env: SETUP_CMD='build_sphinx' # don't crash for warnings

        # Try Astropy development version (which is no longer compatible with py2.7)
        - python: 3.5
          env: ASTROPY_VERSION=development SETUP_CMD='test'
        - python: 3.6
          env: ASTROPY_VERSION=development SETUP_CMD='test'

        # Try with optional dependencies disabled
        - python: 2.7
          env: SETUP_CMD='test'
               CONDA_DEPENDENCIES='matplotlib=1.5'
               PIP_DEPENDENCIES=''
        - python: 3.5
          env: SETUP_CMD='test'
               CONDA_DEPENDENCIES='matplotlib=1.5'
               PIP_DEPENDENCIES=''

    allow_failures:
    #  Optional dependencies disabled
        - python: 2.7
          env: SETUP_CMD='test'
               CONDA_DEPENDENCIES='matplotlib=1.5'
               PIP_DEPENDENCIES=''
        - python: 3.5
          env: SETUP_CMD='test'
               CONDA_DEPENDENCIES='matplotlib=1.5'
               PIP_DEPENDENCIES=''

install:
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh

    # Make sure that interactive matplotlib backends work
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start


script:
   - python setup.py $SETUP_CMD
   # some extras for future use
   # right now, run_tests is required
   # but py.test works, kinda
   - if [ $SETUP_CMD == 'test' ]; then py.test -x pyspeckit/spectrum/tests/test_units.py; fi
